openapi: 3.0.1
info:
  title: The user API
  version: "1"

components:
  schemas:
    UserStatus:
      type: string
      title: User Status
      description: 'the definition of userstatus'
      enum:
        - active
        - inactive
        - testPending
    GeneralResponse:
      required:
      - content
      - code
      type: object
      properties:
        content:
          type: string
          example: ""
        code:
          type: string
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
