openapi: 3.0.1
info:
  title: The image API
  version: "1"
servers:
- url: /api/v1
paths:
  /images/{id}:
    get:
      operationId: getImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          pattern: '^[0-9a-zA-Z\-]+$'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/GeneralResponse'
